title: Acorda Brasil
description: Observatório Acorda Brasil
theme: just-the-docs

url: https://acordabrasil.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
