title: Acorda Brasil
description: Observatório Acorda Brasil
theme: just-the-docs

url: https://acordabrasil.github.io

aux_links:
  Fórum: https://acordabrasil.discourse.group/
  
ga_tracking: G-7BH12KMWEQ
ga_tracking_anonymize_ip: true

